/*
 * This source file was generated by the Gradle 'init' task
 */
package University;

import java.util.ArrayList;
import java.util.List;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Scanner;
import java.util.*;


public class App {

    public static void main(String[] args) {
        System.out.println("student info...");

        List<Student> studentData = new ArrayList<>();
        List<Teacher> teacherData = new ArrayList<>();
        
        studentData.add(new Student(14,  "yeisrael" , "sw", "d", 2028) );
        studentData.add(new Student(13, "yeab", "sw", "d", 2028));

        teacherData.add(new Teacher(14,  "yeisrael" , "sw"));
        teacherData.add(new Teacher(14,  "yeisrael" , "sw"));

        Student.addStudent(studentData);
        Teacher.addTeacher(teacherData);

        Student.showStudent();
        Teacher.showTeacher();

    }
}
